### ISSUE TITLE
Recognize embedded CoffeeScript in HTML <script type='text/coffeescript'> tags

### ISSUE THREAD

**Issue by Nieralyte** [SublimeText/CoffeeScript#207] opened 2015-04-01 14:07 UTC

**Comment by Nieralyte** [comment] 2015-04-01 16:27
alright. i did the following modifications to the `HTML.tmLanguage` file which is located in a compressed archive `C:\ProgramFiles\SublimeText3\Packages\HTML.sublime-package` (or similar path):

i replaced:

```xml
<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
```

...with:

```xml
<string>(?:^\s+)?(&lt;)((?i:script))\b(?=[^&gt;]*type *=[^&gt;]*text/javascript)\b(?![^&gt;]*/&gt;)</string>
```

(so embedding regular javascript works with `<script type='text/javascript'>` tag)

and added:

```xml
<dict>
	<key>begin</key>
	<string>(?:^\s+)?(&lt;)((?i:script))\b(?=[^&gt;]*type *=[^&gt;]*text/coffeescript)\b(?![^&gt;]*/&gt;)</string>
	<key>beginCaptures</key>
	<dict>
		<key>1</key>
		<dict>
			<key>name</key>
			<string>punctuation.definition.tag.begin.html</string>
		</dict>
		<key>2</key>
		<dict>
			<key>name</key>
			<string>entity.name.tag.script.html</string>
		</dict>
	</dict>
	<key>end</key>
	<string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
	<key>endCaptures</key>
	<dict>
		<key>2</key>
		<dict>
			<key>name</key>
			<string>punctuation.definition.tag.html</string>
		</dict>
	</dict>
	<key>name</key>
	<string>source.coffee.embedded.html</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#tag-stuff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)((?i:script))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
	</array>
</dict>
```

(so embedding coffeescript works with `<script type='text/coffeescript'>` tag)

**Comment by deathaxe** [comment] 2024-08-26 16:22
Duplicate of #122

**Closed by deathaxe** 2024-08-26 16:22 UTC
