### ISSUE TITLE
Add support for Coffee-React

### ISSUE THREAD

**Issue by IvanTorresEdge** [SublimeText/CoffeeScript#148] opened 2014-05-12 07:09 UTC
https://github.com/jsdf/coffee-react

**Comment by felixhao28** [comment] 2015-03-17 07:17
I'd like to add that when I type the last slash in `<div></` ST tries to complete the closing tag, resulting `<div></div>`, which is a very nice experience.

Maybe I am asking too much.

**Comment by FredyC** [comment] 2015-04-15 05:35
Hm, reactjs/sublime-react is deprecated now and they suggest to use babel/babel-sublime, but I don't see any support for CJSX files there. My main concern is, that I have configured BetterCoffeescript to "checkSyntaxOnSave" a leaving syntax set as CoffeeScript generates error when using JSX.

Would be really helpful if BS would allow to configure exact binary to execute instead of looking for coffee executable in "binDir".

**Comment by chrisvfritz** [comment] 2015-04-18 16:24
:+1: It looks like [babel-sublime will never support CJSX](https://github.com/babel/babel-sublime/issues/96), so this seems like the logical place to add full support. I'm redirecting folks from babel-sublime to this issue.

**Comment by zertosh** [comment] 2015-04-18 18:44
As the maintainer of babel-sublime, I can confirm that we will not support CJSX. If sublime-better-coffeescript takes on supporting CJSX, I'd be more than happy to drop in note in the README referring users over here.

**Comment by mvaivre** [comment] 2015-06-18 08:49
+1 for CJSX support!

**Comment by jamesfzhang** [comment] 2015-08-10 18:33
:+1:

**Closed** 2024-08-26 17:47 UTC
